const SMALL_CASE_ALPHABETS = 'qwertyuiopasdfghjklzxcvbnm';
const BIG_CASE_ALPHABETS = 'QWERTYUIOPASDFGHJKLZXCVBNM';
const NUMBERS = '1234567890';
const SYMBOLS = '`~!@#$%^&*()_+-=[]\ {}|;:",./<>?\'';

function clearScreen() {
  console.clear();
}

function getChoise() {
  const message = "This is a Enigma Machine. You can either decrypt or encrypt a script based on the KEY.\nSelect an option : \n\n 1. Encrypt\n 2. Decrypt";
  const selectedChoise = +prompt(message);

  clearScreen();

  if (selectedChoise === 1 || selectedChoise === 2) {
    return selectedChoise;
  }

  console.log('Select a Valid option..🙂');

  return getChoise();
}

function areSameCharsFound(character, key, index) {
  for (let currentIndex = index; currentIndex < key.length; currentIndex += 2) {
    if (character === key[currentIndex]) {
      return true;
    }
  }

  return false;
}

function isCharacterEncrypted(character, key) {
  for (let index = 0; index < key.length; index += 2) {
    if (character === key[index])
      return true;
  }

  return false;
}

function getRandomNoBetween(to, from) {
  return from + Math.ceil(Math.random() * (to - from));
}

function getRandomCharFromString(string) {
  return string[getRandomNoBetween(0, string.length - 1)];
}

function getRandomChar() {
  const randomNumberForChar = getRandomNoBetween(0, 4);

  switch (randomNumberForChar) {
    case 1:
      return getRandomChar(SMALL_CASE_ALPHABETS);
    case 2:
      return getRandomCharFromString(BIG_CASE_ALPHABETS);
    case 3:
      return getRandomCharFromString(NUMBERS);
    }

    return getRandomCharFromString(SYMBOLS);
}

function isEncryptedCharUsed(character, key) {
  for (let index = 1; index < key.length; index += 2) {
    if (character === key[index]) {
      return true;
    }
  }

  return false;
}

function getEncryptedCharacter(character, key) {
  const randomChar = getRandomChar();

  if (isEncryptedCharUsed(randomChar, key)) {
    return getEncryptedCharacter(character, key);
  }

  return randomChar;
}

function getKeyFromComputer(text) {
  let key = '';

  for (let index = 0; index < text.length; index++) {
    const character = text[index];

    if (!isCharacterEncrypted(character, key)) {
      key += character + getEncryptedCharacter(character, key);
    }
  }
  console.log("\n\nThe KEY generated by Computer :", key);

  return key;
}

function getReplacementForChar(character, key) {
  for (let index = 0; index < key.length; index += 2) {
    if (character === key[index]) {
      return key[index + 1];
    }
  }

  return character;
}

function convertText(key, text) {
  let convertedText = '';

  for (let index = 0; index < text.length; index++) {
    convertedText += getReplacementForChar(text[index], key);
  }

  return convertedText;
}

function isKeyValid(key) {
  if (key === '') {
    console.log("Indvalid KEY..🙂");

    return false;
  }

  for (let index = 1; index < key.length; index += 2) {
    if (areSameCharsFound(key[index], key, index + 2)) {
      console.log("Indvalid KEY..🙂");

      return false;
    }
  }

  return true;
}

function getKeyFromUser(text) {
  const key = prompt("\nEnter / Paste the KEY here :");

  if (!isKeyValid(key)) {
    return getKeyFromUser(text);
  }

  return key;
}

function getKeyToEncrypt(text) {
  const keyChoise = +prompt('\n\nSelect an option for the KEY : \n\n 1.User had a KEY\n 2.Let Computer generate a KEY');

  if (keyChoise !== 1 && keyChoise !== 2) {
    clearScreen();

    console.log('Enter a Valid option..🙂 ');

    return getKeyToEncrypt(text);
  }

  const key = keyChoise === 1 ? getKeyFromUser(text) : getKeyFromComputer(text);

  return key;
}

function reverse(index, string) {
  if (index === string.length - 1) {
    return string[index];
  }

  return reverse(index + 1, string) + string[index];
}

function getKey(text, processType) {
  if (processType === 'encrypt') {
    return getKeyToEncrypt(text);
  }

  if (processType === 'decrypt') {
    return reverse(0, getKeyFromUser(text));
  }
}

function processToPerform(processType) {
  const TEXT = prompt('Enter / Paste text here that you want to ' + processType + ' :');

  if (TEXT === '') {
    clearScreen();
    console.log('ANYTHING is better than NOTHING. Please enter any text..🙂 \n');

    return processToPerform(processType);
  }

  const KEY = getKey(TEXT, processType);
  const CONVERTED_TEXT = convertText(KEY, TEXT);

  console.log("\nThe " + processType + "ed text :", CONVERTED_TEXT, "\n\n\n\n");

  return CONVERTED_TEXT;
}

function encryptOrDectypt() {
  console.clear();

  const userChoise = getChoise();
  let encryptedOrDectyptedText = '';

  if (userChoise === 1) {
    encryptedOrDectyptedText = processToPerform('encrypt');
  }

  if (userChoise === 2) {
    encryptedOrDectyptedText = processToPerform('decrypt');
  }

  return encryptedOrDectyptedText;
}

encryptOrDectypt();
